{
 "title": "vSphere - Compute",
 "description": "vSphere Compute metrics with telegraf and influxdb database",
 "tags": [
  "VMware",
  "compute",
  "telegraf",
  "influxdb"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vmw_inter",
    "label": "Intervalo",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vmw_vcenter",
    "label": "vCenter Server",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=vcenter"
   },
   {
    "name": "vmw_dc",
    "label": "vCenter Data Center",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=dcname WHERE \"vcenter\" =~ /$vmw_vcenter/"
   },
   {
    "name": "vmw_cluster",
    "label": "vSphere Cluster",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=clustername WHERE \"vcenter\" =~ /$vmw_vcenter/"
   },
   {
    "name": "vmw_esxihost",
    "label": "vSphere ESXi host",
    "query": "SHOW TAG VALUES FROM vsphere_host_cpu WITH KEY=esxhostname WHERE \"vcenter\" =~ /$vmw_vcenter/"
   },
   {
    "name": "vmw_ds",
    "label": "vSphere Data Store",
    "query": "SHOW TAG VALUES FROM vsphere_datastore_datastore WITH KEY=source WHERE \"vcenter\" =~ /$vmw_vcenter/  "
   }
  ]
 },
 "panels": [
  {
   "title": "Datastore Summary ",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES CARDINALITY FROM vsphere_datastore_datastore WITH KEY=source WHERE (\"dcname\" =~ /^$vmw_dc$/);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM current usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dcname", "operator": "=~", "value": "/^$vmw_dc$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$vmw_cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU current usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 10, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_cpu",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dcname", "operator": "=~", "value": "/^$vmw_dc$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$vmw_cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "vSphere Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 14, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_sys",
     "query": "SELECT mean(\"usage_average\") FROM \"vsphere_host_cpu\" WHERE (\"dcname\" =~ /^$vmw_dc$/ AND \"clustername\" =~ /^$vmw_cluster$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dcname", "operator": "=~", "value": "/^$vmw_dc$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$vmw_cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Power ON VM Summary",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "query": "SHOW TAG VALUES CARDINALITY FROM vsphere_vm_cpu WITH KEY=source WHERE (\"dcname\" =~ /^$vmw_dc$/ AND \"clustername\" =~ /^$vmw_cluster$/);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Power ON Hosts Summary",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "query": "SHOW TAG VALUES CARDINALITY FROM vsphere_host_cpu WITH KEY=source WHERE (\"dcname\" =~ /^$vmw_dc$/ AND \"clustername\" =~ /^$vmw_cluster$/);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Power ON vCenter Summary",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "query": "SHOW TAG VALUES CARDINALITY FROM vsphere_vm_cpu WITH KEY=vcenter WHERE (\"dcname\" =~ /^$vmw_dc$/ AND \"clustername\" =~ /^$vmw_cluster$/);",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Cluster RAM Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent", "label": "Usage Average %" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsphere_host_mem",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dcname", "operator": "=~", "value": "/^$vmw_dc$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$vmw_cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent", "label": "Uso promedio %" }
   ],
   "targets": [
    {
     "alias": "$tag_clustername",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clustername" ], "type": "tag" }
     ],
     "measurement": "vsphere_host_cpu",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "dcname", "operator": "=~", "value": "/^$vmw_dc$/" },
      { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$vmw_cluster$/" }
     ]
    }
   ]
  }
 ]
}